INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (1, 999.999, 999.999, 'unknown city', 'unknown city', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (2, 52.232, 21.007, 'warsaw', 'warsaw', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (3, 53.902, 27.561, 'minsk', 'minsk', 'belarus', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (4, 55.479, 37.327, 'moscow', 'moscow', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (5, 46.487, 30.739, 'odessa', 'odessa', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (6, 50.45, 30.524, 'kiev', 'kiev', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (7, 49.99, 36.23, 'kharkiv', 'kharkiv', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (8, 46.973, 46.973, 'mykolaiv', 'mykolaiv', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (9, 59.934, 30.335, 'st_petersburg', 'st_petersburg', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (10, 53.798, 21.577, 'mikolajki', 'mikolajki', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (11, 51.109, 17.033, 'wroclaw', 'wroclaw', 'poland', 'Świdnicka, 50-064 Wrocław');
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (12, 50.062, 19.937, 'krakow', 'krakow', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (13, 54.348, 18.645, 'gdansk', 'gdansk', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (14, 49.842, 24.032, 'lviv', 'lviv', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (15, 52.401, 16.92, 'poznan', 'poznan', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (16, 54.71, 20.511, 'kaliningrad', 'kaliningrad', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (17, 50.908, 34.794, 'sumy', 'sumy', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (18, 49.587, 34.546, 'poltava', 'poltava', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (19, 47.024, 28.832, 'chisinau', 'chisinau', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (20, 51.251, 22.57, 'lublin', 'lublin', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (21, 50.26, 19.022, 'katowice', 'katowice', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (22, 53.43, 14.551, 'szczecin', 'szczecin', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (23, 48.923, 24.711, 'ivano-frankivsk', 'ivano-frankivsk', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (24, 54.687, 25.282, 'vilnius', 'vilnius', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (25, 56.949, 24.105, 'riga', 'riga', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (26, 53.122, 18, 'bydgoszcz', 'bydgoszcz', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (27, 59.437, 24.745, 'tallin', 'tallin', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (28, 50.617, 26.249, 'rivne', 'rivne', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (29, 50.037, 22.004, 'rzeszow', 'rzeszow', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (30, 51.4, 21.165, 'radom', 'radom', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (31, 51.769, 19.457, 'lodz', 'lodz', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (32, 50.812, 19.113, 'czestochowa', 'czestochowa', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (33, 54.156, 19.404, 'elblag', 'elblag', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (34, 55.782, 49.124, 'kazan', 'kazan', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (35, 47.497, 19.04, 'budapest', 'budapest', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (36, 53.127, 23.162, 'bialystok', 'bialystok', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (37, 51.844, 16.58, 'leszno', 'leszno', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (38, 53.147, 16.743, 'pila', 'pila', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (39, 49.834, 18.282, 'ostrava', 'ostrava', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (40, 53.01, 18.605, 'torun', 'torun', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (41, 49.784, 22.789, 'przemysl', 'przemysl', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (42, 50.721, 23.26, 'zamosc', 'zamosc', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (43, 51.136, 23.494, 'chelm', 'chelm', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (44, -27.597, -48.55, 'florianopolis', 'florianopolis', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (45, 54.191, 16.177, 'koszalin', 'koszalin', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (46, 51.928, 15.549, 'zielona_gora', 'zielona_gora', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (47, 44.818, 20.457, 'belgrad', 'belgrad', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (48, 44.436, 26.103, 'bucharest', 'bucharest', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (49, 42.442, 19.262, 'podgorica', 'podgorica', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (50, 43.512, 16.44, 'split', 'split', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (51, 50.087, 14.421, 'prague', 'prague', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (52, 49.707, 15.295, 'hradec', 'hradec', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (53, 51.957, 14.737, 'gubin', 'gubin', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (54, 53.777, 20.478, 'olsztyn', 'olsztyn', '', null);
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (55, 51.071, 17.004, 'wroclaw2', 'wroclaw', 'poland', 'Zimowa 15c, 53-018');
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (56, 52.212, 20.977, 'warsaw2', 'warsaw', 'poland', 'Grójecka 76, 02-359');
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (57, 52.245, 21.084, 'warsaw3', 'warsaw', 'poland', 'Rondo Wiatraczna, 04-078');
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (58, 52.239, 20.956, 'warsaw4', 'warsaw', 'poland', 'Aleja Prymasa Tysiąclecia, 01-404');
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (59, 50.512, 30.497, 'kiev2', 'kiev', 'ukraine', 'Levko Lukianenko Street, Obolon, 04207');
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (60, 50.447, 30.39, 'kiev3', 'kiev', 'ukraine', 'Sviatoshynska Street, Sviatoshyn, 03148');
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (61, 50.454, 30.522, 'kiev4', 'kiev', 'ukraine', 'Mykhailivska Street, 20-Б, Центр, 01028');
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (62, 52.095, 23.705, 'brest', 'brest', 'belarus', '224012 Brest, Маскоўскі раён, вуліца Гогаля, 81');
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (63, 54.329, 19.109, 'stegna', 'stegna', 'poland', 'Władysława Jagiełły 12, 82-103 Stegna');
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (64, 54.515, 18.541, 'gdynia', 'gdynia', 'poland', 'Świętojańska 53, 81-391 Gdynia');
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (65, 51.762, 18.089, 'kalisz', 'kalisz', 'poland', 'Główny Rynek 17, 62-800 Kalisz');
INSERT INTO Locations (id, latitude, longitude, shortName, city, country, address) VALUES (66, 38.713, -9.159, 'lisbon1', 'lisbon', 'portugal', 'Estrela, Praça da Estrela, 1200-667 Lisbon');
