from database_api import create_phonetics, create_expressions


def phonetics_insert_console():
    phonetics = [
        ("Добрый вечер", "Dó-bri ve-chér"),
        ("Где находится...?", "Gdê na-kho-dí-tsya...?"),
        ("Как вас зовут?", "Kak vas zo-vut?"),
        ("Я люблю тебя", "Ya lyu-blyu te-bya"),
        ("Можно ли...?", "Mózh-na li...?"),
        ("Что это?", "Shto é-tâ?"),
        ("Когда?", "Kag-dá?"),
        ("Почему?", "Pach-e-mú?"),
        ("Кто?", "Kto?"),
        ("Как?", "Kak?"),
        ("Где?", "Gdê?"),
        ("Что вы сказали?", "Shto vy ská-za-li?"),
        ("Повторите, пожалуйста", "Pav-ta-ryi-te, pa-zhá-luysta"),
        ("Я не знаю", "Ya nye zna-yu"),
        ("Я заблудился", "Ya zab-lu-díl-sya"),
        ("Какой адрес?", "Ka-kóy ad-res?"),
        ("У вас есть...?", "U vas yest’...?"),
        ("Можно мне...?", "Mózh-na mne...?"),
        ("Я хочу...", "Ya kha-chú..."),
        ("Могу я...?", "Ma-gu ya...?"),
        ("Говорите медленнее, пожалуйста", "Go-va-rí-te myed-len-né-ye, pa-zhá-luysta"),
        ("Счастливого пути", "Scha-stli-vó-va pu-tí"),
        ("Удачи", "U-dá-chi"),
        ("С праздником", "S praz-dni-kom"),
        ("С Днём Рождения", "S Dnyóm Rozh-dé-ní-ya"),
        ("Мои соболезнования", "Ma-í so-ba-léz-no-va-ni-ya"),
        ("До встречи", "Da vstré-chi"),
        ("Это правда?", "É-tâ prav-da?"),
        ("Я согласен", "Ya sa-gla-syen"),
        ("Я не согласен", "Ya nye sa-gla-syen"),
        ("Мне нравится", "Mne nrá-vi-tsa"),
        ("Мне не нравится", "Mne nye nrá-vi-tsa"),
        ("Я устал", "Ya us-tál"),
        ("Я голоден", "Ya go-lo-den"),
        ("Я хочу пить", "Ya kha-chú pit’"),
        ("Я болею", "Ya ba-lé-yu"),
        ("У меня болит...", "U me-nya ba-lít..."),
        ("Какой сегодня день?", "Ka-kóy sye-vo-dn-ya dên’?"),
        ("Который час?", "Ka-tó-ryi chás?"),
        ("Сколько вам лет?", "Skol’-ka vam lyet?"),
        ("Где ты живёшь?", "Gdê ty zhiv-yósh?"),
        ("Откуда ты?", "Ot-kú-da ty?"),
        ("Что ты делаешь?", "Shto ty dýe-lá-esh’?"),
        ("Что случилось?", "Shto sloo-chí-los’?"),
        ("Ты замужем?", "Ty za-mú-zhem?"),
        ("Ты женат?", "Ty zhe-nát?"),
        ("У вас есть дети?", "U vas yest’ dýe-ti?"),
        ("Какой ваш телефон?", "Ka-kóy vash te-le-fón?"),
        ("Какие планы на сегодня?", "Ka-kí-ye plá-ny na sye-vo-dn-yâ?"),
        ("Ты любишь читать?", "Ty lyu-bish’ chi-tát’?"),
        ("Какая твоя любимая книга?", "Ka-ká-ya tvá-ya lyu-bí-má-ya kní-ga?"),
        ("Какая твоя любимая музыка?", "Ka-ká-ya tvá-ya lyu-bí-má-ya mú-zi-ka?"),
        ("Какие фильмы ты любишь?", "Ka-kí-ye fí-lmy ty lyu-bish’?"),
        ("Ты занимаешься спортом?", "Ty za-ni-má-yesh’sya spór-tom?"),
        ("Как пройти до...?", "Kak pro-í-ti do...?"),
        ("Можно вашу помощь?", "Mózh-na vá-shu po-móshch’?"),
        ("Могу я вам помочь?", "Ma-gu ya vam po-mó-ch?"),
        ("Не беспокойтесь", "Nye bes-po-kóy-tes’"),
        ("Скорую помощь", "Skó-ru-yu po-móshch’"),
        ("Где ближайшая аптека?", "Gdê blizhá-ya-ya ap-té-ka?"),
        ("Я забронировал номер", "Ya za-bro-ní-ro-val nó-mer"),
        ("Мне нужен номер на одну ночь", "Mne nu-zhén nó-mer na ad-nú noch’"),
        ("Сколько стоит за ночь?", "Skol’-ka stó-it za noch’?"),
        ("Вы принимаете кредитные карты?", "Vy pri-ny-má-ye-te kre-dít-ny-e kár-ty?"),
        ("Где ближайший банкомат?", "Gdê blizhá-yi shí ban-ko-mát?"),
        ("Сколько времени займёт?", "Skol’-ka vré-mé-ni zay-myót?"),
        ("Это далеко?", "É-tâ da-lé-kó?"),
        ("Можно счёт, пожалуйста?", "Mózh-na schyót, pa-zhá-luysta?"),
        ("Могу я расплатиться наличными?", "Ma-gu ya ras-plá-ti-tsa na-lí-chny-mi?"),
        ("Где ближайшая станция метро?", "Gdê blizhá-ya-ya stán-tsi-ya me-tró?"),
        ("Как доехать до центра города?", "Kak do-ye-khat’ do tsén-tra gó-ro-da?"),
        ("У меня есть вопрос", "U me-nya yest’ va-prós"),
        ("Говорите громче, пожалуйста", "Go-va-rí-te gróm-ché, pa-zhá-luysta"),
        ("Скажите ещё раз", "Ská-zhí-te yeshchó raz"),
        ("Откройте, пожалуйста", "Ot-kró-yte, pa-zhá-luysta"),
        ("Закройте, пожалуйста", "Za-kró-yte, pa-zhá-luysta"),
        ("Войдите", "Vói-dí-te"),
        ("Выходите", "Vý-kho-dí-te"),
        ("Приятного аппетита", "Pri-yát-na-va ap-pi-tí-ta")
    ]

    create_phonetics(phonetics)


def insert_expressions_console():


    expressions = [
        ("Onde está...?", "Where is...?"),
        ("Qual é o seu nome?", "What's your name?"),
        ("Eu te amo", "I love you"),
        ("É possível...?", "Is it possible...?"),
        ("O que é isso?", "What is this?"),
        ("Quando?", "When?"),
        ("Por quê?", "Why?"),
        ("Quem?", "Who?"),
        ("Como?", "How?"),
        ("Onde?", "Where?"),
        ("O que você disse?", "What did you say?"),
        ("Por favor, repita", "Please repeat"),
        ("Eu não sei", "I don't know"),
        ("Estou perdido", "I'm lost"),
        ("Qual é o endereço?", "What is the address?"),
        ("Você tem...?", "Do you have...?"),
        ("Posso ter...?", "Can I have...?"),
        ("Eu quero...", "I want..."),
        ("Posso...?", "May I...?"),
        ("Fale mais devagar, por favor", "Speak slower, please"),
        ("Tenha uma boa viagem", "Have a good trip"),
        ("Boa sorte", "Good luck"),
        ("Boas festas", "Happy holiday"),
        ("Feliz Aniversário", "Happy Birthday"),
        ("Meus pêsames", "My condolences"),
        ("Até logo", "See you later"),
        ("É verdade?", "Is it true?"),
        ("Eu concordo", "I agree"),
        ("Eu discordo", "I disagree"),
        ("Eu gosto", "I like it"),
        ("Eu não gosto", "I don't like it"),
        ("Estou cansado", "I'm tired"),
        ("Estou com fome", "I'm hungry"),
        ("Estou com sede", "I'm thirsty"),
        ("Estou doente", "I'm sick"),
        ("Eu tenho uma dor em...", "I have a pain in..."),
        ("Que dia é hoje?", "What day is it today?"),
        ("Que horas são?", "What time is it?"),
        ("Quantos anos você tem?", "How old are you?"),
        ("Onde você mora?", "Where do you live?"),
        ("De onde você é?", "Where are you from?"),
        ("O que você está fazendo?", "What are you doing?"),
        ("O que aconteceu?", "What happened?"),
        ("Você é casada?", "Are you married? (to a woman)"),
        ("Você é casado?", "Are you married? (to a man)"),
        ("Você tem filhos?", "Do you have children?"),
        ("Qual é o seu número de telefone?", "What’s your phone number?"),
        ("Quais são seus planos para hoje?", "What are your plans for today?"),
        ("Você gosta de ler?", "Do you like reading?"),
        ("Qual é o seu livro favorito?", "What is your favorite book?"),
        ("Qual é a sua música favorita?", "What is your favorite music?"),
        ("Que filmes você gosta?", "What movies do you like?"),
        ("Você pratica esportes?", "Do you do sports?"),
        ("Como chegar a...?", "How to get to...?"),
        ("Posso ter a sua ajuda?", "Can I have your help?"),
        ("Posso te ajudar?", "Can I help you?"),
        ("Não se preocupe", "Don’t worry"),
        ("Chame uma ambulância", "Call an ambulance"),
        ("Onde fica a farmácia mais próxima?", "Where is the nearest pharmacy?"),
        ("Eu tenho uma reserva", "I have a reservation"),
        ("Eu preciso de um quarto para uma noite", "I need a room for one night"),
        ("Quanto custa por noite?", "How much is per night?"),
        ("Vocês aceitam cartões de crédito?", "Do you accept credit cards?"),
        ("Onde fica o caixa eletrônico mais próximo?", "Where is the nearest ATM?"),
        ("Quanto tempo vai demorar?", "How long will it take?"),
        ("É longe?", "Is it far?"),
        ("Pode trazer a conta, por favor?", "Can I have the bill, please?"),
        ("Posso pagar em dinheiro?", "Can I pay in cash?"),
        ("Onde fica a estação de metrô mais próxima?", "Where is the nearest metro station?"),
        ("Como chegar ao centro da cidade?", "How to get to the city center?"),
        ("Eu tenho uma pergunta", "I have a question"),
        ("Fale mais alto, por favor", "Speak louder, please"),
        ("Diga novamente", "Say it again"),
        ("Abra, por favor", "Open, please"),
        ("Feche, por favor", "Close, please"),
        ("Entre", "Come in"),
        ("Saia", "Go out"),
        ("Bom apetite", "Enjoy your meal")]

    languageEng = 'portuguese'



    # expressions = [
    #     ("Привет", "Hello"),
    #     ("Как дела?", "How are you?"),
    #     ("Спасибо", "Thank you"),
    #     ("Пожалуйста", "Please"),
    #     ("Пожалуйста", "You're welcome"),
    #     ("Да", "Yes"),
    #     ("Нет", "No"),
    #     ("Извините", "Excuse me"),
    #     ("Извините", "Sorry"),
    #     ("До свидания", "Goodbye"),
    #     ("Доброе утро", "Good morning"),
    #     ("Добрый день", "Good afternoon"),
    #     ("Добрый вечер", "Good evening"),
    #     ("Спокойной ночи", "Good night"),
    #     ("Я не понимаю", "I don't understand"),
    #     ("Где находится...?", "Where is...?"),
    #     ("Сколько это стоит?", "How much does it cost?"),
    #     ("Меня зовут...", "My name is..."),
    #     ("Как вас зовут?", "What's your name?"),
    #     ("Очень приятно", "Nice to meet you"),
    #     ("До скорого", "See you soon"),
    #     ("Я люблю тебя", "I love you"),
    #     ("Помогите!", "Help!"),
    #     ("Можно ли...?", "Is it possible...?"),
    #     ("Что это?", "What is this?"),
    #     ("Когда?", "When?"),
    #     ("Почему?", "Why?"),
    #     ("Кто?", "Who?"),
    #     ("Как?", "How?"),
    #     ("Где?", "Where?"),
    #     ("Что вы сказали?", "What did you say?"),
    #     ("Повторите, пожалуйста", "Please repeat"),
    #     ("Я не знаю", "I don't know"),
    #     ("Я заблудился", "I'm lost"),
    #     ("Какой адрес?", "What is the address?"),
    #     ("У вас есть...?", "Do you have...?"),
    #     ("Можно мне...?", "Can I have...?"),
    #     ("Я хочу...", "I want..."),
    #     ("Могу я...?", "May I...?"),
    #     ("Вы говорите по-английски?", "Do you speak English?"),
    #     ("Говорите медленнее, пожалуйста", "Speak slower, please"),
    #     ("Счастливого пути", "Have a good trip"),
    #     ("Поздравляю", "Congratulations"),
    #     ("Удачи", "Good luck"),
    #     ("С праздником", "Happy holiday"),
    #     ("С Днём Рождения", "Happy Birthday"),
    #     ("Мои соболезнования", "My condolences"),
    #     ("До встречи", "See you later"),
    #     ("Это правда?", "Is it true?"),
    #     ("Я согласен", "I agree"),
    #     ("Я не согласен", "I disagree"),
    #     ("Мне нравится", "I like it"),
    #     ("Мне не нравится", "I don't like it"),
    #     ("Я устал", "I'm tired"),
    #     ("Я голоден", "I'm hungry"),
    #     ("Я хочу пить", "I'm thirsty"),
    #     ("Я болею", "I'm sick"),
    #     ("У меня болит...", "I have a pain in..."),
    #     ("Как тебя зовут?", "What’s your name?"),
    #     ("Какой сегодня день?", "What day is it today?"),
    #     ("Который час?", "What time is it?"),
    #     ("Сколько вам лет?", "How old are you?"),
    #     ("Где ты живёшь?", "Where do you live?"),
    #     ("Откуда ты?", "Where are you from?"),
    #     ("Что ты делаешь?", "What are you doing?"),
    #     ("Что случилось?", "What happened?"),
    #     ("Ты замужем?", "Are you married? (to a woman)"),
    #     ("Ты женат?", "Are you married? (to a man)"),
    #     ("У вас есть дети?", "Do you have children?"),
    #     ("Какой ваш телефон?", "What’s your phone number?"),
    #     ("Какие планы на сегодня?", "What are your plans for today?"),
    #     ("Ты любишь читать?", "Do you like reading?"),
    #     ("Какая твоя любимая книга?", "What is your favorite book?"),
    #     ("Какая твоя любимая музыка?", "What is your favorite music?"),
    #     ("Какие фильмы ты любишь?", "What movies do you like?"),
    #     ("Ты занимаешься спортом?", "Do you do sports?"),
    #     ("Как пройти до...?", "How to get to...?"),
    #     ("Можно вашу помощь?", "Can I have your help?"),
    #     ("Могу я вам помочь?", "Can I help you?"),
    #     ("Не беспокойтесь", "Don’t worry"),
    #     ("Скорую помощь", "Call an ambulance"),
    #     ("Вызовите полицию", "Call the police"),
    #     ("Мне нужно к врачу", "I need a doctor"),
    #     ("Где ближайшая аптека?", "Where is the nearest pharmacy?"),
    #     ("Я забронировал номер", "I have a reservation"),
    #     ("Мне нужен номер на одну ночь", "I need a room for one night"),
    #     ("Сколько стоит за ночь?", "How much is per night?"),
    #     ("Вы принимаете кредитные карты?", "Do you accept credit cards?"),
    #     ("Где ближайший банкомат?", "Where is the nearest ATM?"),
    #     ("Сколько времени займёт?", "How long will it take?"),
    #     ("Это далеко?", "Is it far?"),
    #     ("Можно счет, пожалуйста?", "Can I have the bill, please?"),
    #     ("Могу я расплатиться наличными?", "Can I pay in cash?"),
    #     ("Где ближайшая станция метро?", "Where is the nearest metro station?"),
    #     ("Как доехать до центра города?", "How to get to the city center?"),
    #     ("Вы можете мне помочь?", "Can you help me?"),
    #     ("У меня есть вопрос", "I have a question"),
    #     ("Говорите громче, пожалуйста", "Speak louder, please"),
    #     ("Скажите ещё раз", "Say it again"),
    #     ("Откройте, пожалуйста", "Open, please"),
    #     ("Закройте, пожалуйста", "Close, please"),
    #     ("Войдите", "Come in"),
    #     ("Выходите", "Go out"),
    #     ("Приятного аппетита", "Enjoy your meal"),
    #     ("Сколько вам лет?", "How old are you?")]
    #
    # languageEng = 'russian'

    create_expressions(expressions, languageEng)