SOUND_FILES_DIRECTORY = "sound"
DATABASE_FILE_PATH = "database/langum.db"
TARGET_FOLDER_PATH_DB_INFO = "C:/Users/pedro/StudioProjects/langum/jsons"
FILENAME_NO_EXTENSION = "DB_INFO"
DEFAULT_PORT_NUMBER = 8888


PACK_MEANINGS_JSON_FILENAME_NO_EXTENSION = "pack_meanings"
EXPRESSIONS_JSON_FILENAME_NO_EXTENSION = "expressions"
PHONETICS_JSON_FILENAME_NO_EXTENSION = "phonetics"
